// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg9PmBBogJYEOSTgPNOHzx3Wr25SK_tMc',
    appId: '1:373681007010:web:e2bbf4de9fd4b0d1daeafb',
    messagingSenderId: '373681007010',
    projectId: 'quizapp-a9ec4',
    authDomain: 'quizapp-a9ec4.firebaseapp.com',
    storageBucket: 'quizapp-a9ec4.appspot.com',
    measurementId: 'G-DV064R0XEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE50110HI4gX9uHTMnAVRAGXQDIWi3zkA',
    appId: '1:373681007010:android:4b3fe1c4b52578a2daeafb',
    messagingSenderId: '373681007010',
    projectId: 'quizapp-a9ec4',
    storageBucket: 'quizapp-a9ec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfK9zC1HkV7fssPoy7PE-Xq-lCLwO_ZYg',
    appId: '1:373681007010:ios:7422dd2b447dc897daeafb',
    messagingSenderId: '373681007010',
    projectId: 'quizapp-a9ec4',
    storageBucket: 'quizapp-a9ec4.appspot.com',
    iosClientId: '373681007010-mq0rgbd0n7qqhs1busbpqra89dvmjota.apps.googleusercontent.com',
    iosBundleId: 'com.adamTerh.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfK9zC1HkV7fssPoy7PE-Xq-lCLwO_ZYg',
    appId: '1:373681007010:ios:ab9888c5a09a5f5adaeafb',
    messagingSenderId: '373681007010',
    projectId: 'quizapp-a9ec4',
    storageBucket: 'quizapp-a9ec4.appspot.com',
    iosClientId: '373681007010-noacnrfouavq7g7kc22a7fpii7e1pgun.apps.googleusercontent.com',
    iosBundleId: 'com.adamTerh.myapp.RunnerTests',
  );
}
